### ISSUE TITLE
[BUG] Unexpected token E in JSON at position 0

### ISSUE THREAD

**Issue by qqqllppp** [spruceid/ssx#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In NextJS/NextAuth, when calling `ssx?.signIn()` or `ssx?.signOut()`, the following error occurs in server logs:
```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error Unexpected token E in JSON at position 0 {
  error: {
    message: 'Unexpected token E in JSON at position 0',
    stack: 'SyntaxError: Unexpected token E in JSON at position 0\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSONFromBytes (/home/ben/Documents/learn/new/guide-t3-ssx-minimal/node_modules/next/dist/compiled/undici/index.js:2:4905)\n' +
      '    at successSteps (/home/ben/Documents/learn/new/guide-t3-ssx-minimal/node_modules/next/dist/compiled/undici/index.js:2:4473)\n' +
      '    at /home/ben/Documents/learn/new/guide-t3-ssx-minimal/node_modules/next/dist/compiled/undici/index.js:2:65581\n' +
      '    at node:internal/process/task_queues:141:7\n' +
      '    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n' +
      '    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
    name: 'SyntaxError'
  },
  url: 'http://localhost:3000/api/auth/csrf',
  message: 'Unexpected token E in JSON at position 0'
}
```

### Expected Behavior

No error occurs when calling singIn/singOut

### Steps To Reproduce

Minimum reproducible repo: https://github.com/junhuang-ho/test-t3-ssx
 
in `pages/index.tsx`, after connecting, try the signIn/signOut buttons

**Comment by qqqllppp** [comment]
The issue was because of next-auth: https://github.com/nextauthjs/next-auth/issues/7166#issuecomment-1508439710

The temporary fix:

replace the usage of `SSXNextAuth` from `import { SSXNextAuth } from "@spruceid/ssx-react/next-auth/backend";` with the following component with the emphasis being on `const nonce = await getCsrfToken({ req: { headers: req.headers } });`

```
import { getCsrfToken } from "next-auth/react";
import { SSXServer } from "@spruceid/ssx-server";

export const SSXNextAuthCustom = (ssx: SSXServer) => {
  const credentials = {
    message: {
      label: "Message",
      type: "text",
      placeholder: "0x0",
    },
    signature: {
      label: "Signature",
      type: "text",
      placeholder: "0x0",
    },
    daoLogin: {
      label: "daoLogin",
      type: "boolean",
      placeholder: "false",
    },
    resolveEns: {
      label: "resolveEns",
      type: "boolean",
      placeholder: "false",
    },
  };

  const authorize = async (credentials, req) => {
    try {
      const nonce = await getCsrfToken({ req: { headers: req.headers } });

      // validate signature, nonce and ssx config options
      const { success, error, session } = await ssx.login(
        credentials?.message || "",
        credentials?.signature || "",
        JSON.parse(credentials?.daoLogin || "false"),
        JSON.parse(credentials?.resolveEns || "false"),
        nonce || ""
      );
      const { siwe, signature, daoLogin, ens } = session;
      if (!siwe) return null;

      if (success) {
        return {
          id: `did:pkh:eip155:${siwe.chainId}:${siwe.address}`,
          name: ens?.domain || siwe.address,
          image: ens?.avatarUrl,
          address: siwe.address,
          test: "woo",
        };
      }
    } catch (e) {
      console.error(e);
      return null;
    }
    return null;
  };

  const session = async (sessionData) => {
    const { session, token } = sessionData;
    if (session.user) {
      session.user.name = token.sub;
    }

    return session;
  };

  return { credentials, authorize, session };
};

```

Unfortunately this still remains as only a temporary solution as the underlying issue is at the next-auth package which they dont seem to be interested in patching as this is an "edge case" as per the linked comment
